version: '2'
services:
  db:
    image: mongo:3.0.4
  web:
    build: .
    command: python manage.py runserver 0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
